ARG BASE_IMAGE_TAG=base-latest
FROM quay.io/rhceph-dev/ocsci-osd:${BASE_IMAGE_TAG}

# Environment variables containing various file locations required by
# scripts.
ENV OUTPUT_DIR=/test-run-results

# Install oc as ocs-ci requires it.
ADD https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz /
RUN cd /usr/local/bin && \
    tar -xvf /openshift-client-linux.tar.gz oc

ARG ADDON_TEST_FILE=test-ocs.sh
COPY bin/${ADDON_TEST_FILE} /usr/local/bin/
RUN chmod 755 /usr/local/bin/*.sh

# Run the test suite script when the container is created.
ENV ENTRYPOINT_FILE="/usr/local/bin/${ADDON_TEST_FILE}"
ENTRYPOINT exec "$ENTRYPOINT_FILE"

# vim: ft=dockerfile
